package com.hcmute.shopfee.constant;

public class ErrorConstant {
    public static final String USER_NOT_FOUND = "USER NOT FOUND";
    public static final String CANT_ACCESS = "Do not have the right to access this API";
    public static final String EMPLOYEE_NOT_FOUND = "EMPLOYEE NOT FOUND";
    public static final String REGISTERED_EMAIL = "Email account registered";
    public static final String CREATED_FAILED = "Created failed";
    public static final String UPDATE_FAILED = "Update failed";
    public static final String EMAIL_UNVERIFIED = "Email unverified";
    public static final String CATEGORY_EXISTED = "Category name were existed";
    public static final String CATEGORY_NOT_FOUND = "CATEGORY NOT FOUND";
    public static final String NOT_FOUND = "Not found ";
    public static final String DATE_INVALID = "Date is invalid ";
    public static final String ACCESS_DENIED = "Access Denied";
    public static final String ACCOUNT_BLOCKED = "Account has been locked";
    public static final String PRODUCT_NOT_FOUND = "PRODUCT NOT FOUND";
    public static final String OVER_FIVE_ADDRESS = "Do not add more than 5 addresses";
    public static final String ORDER_NOT_COMPLETED = "Order not completed";
    public static final String INVALID_TOKEN = "Token validation failed";
    public static final String EXPIRED_TOKEN = "Token expired. Please refresh your token.";
    public static final String STOLEN_TOKEN = "Stolen tokens";
    public static final String INVALID_PASSWORD = "INVALID PASSWORD";
    public static final String REQUEST_BODY_INVALID = "Request body is invalid";
    public static final String TOPPING_PRICE_INVALID = "Topping's price is invalid";
    public static final String SIZE_PRODUCT_INVALID = "Size's product is invalid";
    public static final String CANT_DELETE = "Cannot be deleted because this data is related to other data";
    public static final String CONDITION_VALUE_INVALID = "Condition's value is invalid";
    public static final String COUPON_INVALID = "Coupon's value is invalid";
    public static final String COUPON_UNRELEASED = "Coupon is not released";
    public static final String COUPON_OUT_OF_QUANTITY = "Coupon is out of quantity";
    public static final String COUPON_IS_USED = "One coupon has been used";
    public static final String COUPON_DUPLICATED = "Coupon duplicate";
    public static final String COUPON_TYPE_INVALID = "Coupon type is not suitable for this discount";
    public static final String TOTAL_ORDER_INVALID = "Total order is invalid";
    public static final String COUPON_STATUS_UNRELEASED = "Actions cannot be performed on the coupon when it is in the UNRELEASED state";
    public static final String USER_ID_INVALID = "User ID is invalid";
    public static final String COUPON_NOT_RIGHT_TYPE = "Coupon is not the right type";
    public static final String PRINCIPAL_INVALID = "Principle is invalid";
    public static final String SIZE_LIST_CANT_EMPTY = "Size list is empty";
    public static final String PRODUCT_NAME_EXISTED = "Product name already";
}
