package com.hcmute.shopfee.enums;

public enum OrderStatus {
    CREATED,
    ACCEPTED,
    CANCELLATION_REQUEST,
    CANCELLATION_REQUEST_REFUSED,
    CANCELLATION_REQUEST_ACCEPTED,
    PREPARED,
    DELIVERING,
    DELIVERED,
    NOT_RECEIVED,
    CANCELED,
    SUCCEED,
}
